/**
 * Completion command - generates shell completion scripts
 * Supports bash and zsh shells
 *
 * CL-5.2: Shell completion generation
 */

import { CommandHandler, ParsedArguments } from './index.js';

/**
 * Bash completion script template
 */
const BASH_COMPLETION = `# bash completion for my-cli
# Generated by: my-cli completion bash

_my_cli_completion() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  # Completion for main commands
  local commands="help list show config completion --help --version"

  case "\${prev}" in
    my-cli)
      COMPREPLY=($(compgen -W "\${commands}" -- "\${cur}"))
      return 0
      ;;
    list)
      COMPREPLY=($(compgen -W "categories topics" -- "\${cur}"))
      return 0
      ;;
    show)
      # Dynamic topic completion
      local topics=$(my-cli list topics --format json 2>/dev/null | grep -o '"id":"[^"]*"' | cut -d'"' -f4)
      COMPREPLY=($(compgen -W "\${topics}" -- "\${cur}"))
      return 0
      ;;
  esac

  COMPREPLY=($(compgen -W "\${commands}" -- "\${cur}"))
}

complete -o bashdefault -o default -o nospace -F _my_cli_completion my-cli
`;

/**
 * Zsh completion script template
 */
const ZSH_COMPLETION = `#compdef my-cli
# zsh completion for my-cli
# Generated by: my-cli completion zsh

local state

_arguments \\
  '1: :(help list show config completion)' \\
  '2: :(categories topics)' \\
  '*::arg:->args'

case "\$state" in
  args)
    case "\${words[2]}" in
      show)
        local -a topics
        topics=(\${(@f)"\$(my-cli list topics --format json 2>/dev/null | grep -o '"'"'id":"[^"]*"'"'"' | cut -d'"'"'"'"'"' -f4)"}\\n))
        _describe 'topics' topics
        ;;
    esac
    ;;
esac
`;

/**
 * Completion command handler
 * Generates shell completion scripts
 *
 * @param argv - Command arguments
 * @returns Exit code
 */
export const completionCommand: CommandHandler = async (argv: ParsedArguments): Promise<number> => {
  const shell = argv._[1] as string | undefined;

  if (!shell || !['bash', 'zsh'].includes(shell)) {
    console.error('Usage: my-cli completion <bash|zsh>');
    console.error('');
    console.error('Examples:');
    console.error('  # Install bash completion');
    console.error('  my-cli completion bash | sudo tee /usr/local/etc/bash_completion.d/my-cli');
    console.error('');
    console.error('  # Install zsh completion');
    console.error('  my-cli completion zsh | sudo tee /usr/share/zsh/site-functions/_my-cli');
    console.error('');
    console.error('  # Load bash completion in current shell');
    console.error('  source <(my-cli completion bash)');
    return 1;
  }

  // Output appropriate completion script
  if (shell === 'bash') {
    console.log(BASH_COMPLETION);
  } else if (shell === 'zsh') {
    console.log(ZSH_COMPLETION);
  }

  return 0;
};
