#!/bin/sh
# lib/ssh_config.sh — regenerate the ssh config drop-in from the manifest.
#
# Writes ~/.ssh/config.d/devx-delegations (override: $DEVX_SSH_CONFIG_DROPIN)
# and adds a single `Include config.d/devx-delegations` line to ~/.ssh/config.
# AI ssh always goes through a manifest alias (issue #877 L3 allowlist).
#
# Sourced — POSIX sh only. Depends on lib/manifest.sh being sourced first.

ssh_config_dropin_path() {
    printf '%s\n' "${DEVX_SSH_CONFIG_DROPIN:-$HOME/.ssh/config.d/devx-delegations}"
}

ssh_config_main_path() {
    printf '%s\n' "${DEVX_SSH_CONFIG:-$HOME/.ssh/config}"
}

# Expand a leading ~ to $HOME (POSIX-safe, no eval).
ssh_config_expand_tilde() {
    # shellcheck disable=SC2088  # ~ patterns are matched literally, not expanded
    case "$1" in
    "~") printf '%s\n' "$HOME" ;;
    # The pattern in ${1#...} is quoted so the leading ~/ is stripped
    # literally — an unquoted ~/ would itself be tilde-expanded to $HOME/.
    "~/"*) printf '%s/%s\n' "$HOME" "${1#"~/"}" ;;
    *) printf '%s\n' "$1" ;;
    esac
}

# Regenerate the drop-in from all non-revoked manifest entries.
ssh_config_regen() {
    dropin="$(ssh_config_dropin_path)"
    dir="$(dirname "$dropin")"
    [ -d "$dir" ] || mkdir -p "$dir"
    shk="$(manifest_default strict_host_key_checking 2>/dev/null)"
    [ -n "$shk" ] || shk='yes'
    tmp="${dropin}.tmp.$$"
    {
        printf '# AUTO-GENERATED by devx:ssh-delegate — do not edit by hand.\n'
        printf '# Regenerated by sync/add/revoke. Source of truth: %s\n\n' "$(manifest_path)"
        manifest_to_tsv | awk -F'\t' '$11!="true" && NF {print $1}' | while IFS= read -r al; do
            [ -n "$al" ] || continue
            host="$(manifest_get "$al" host)"
            user="$(manifest_get "$al" user)"
            port="$(manifest_eff "$al" port port)"
            [ -n "$port" ] || port=22
            idf="$(manifest_eff "$al" identity_file identity_file)"
            idf="$(ssh_config_expand_tilde "$idf")"
            printf 'Host %s\n' "$al"
            printf '    HostName %s\n' "$host"
            printf '    User %s\n' "$user"
            printf '    Port %s\n' "$port"
            [ -n "$idf" ] && printf '    IdentityFile %s\n' "$idf"
            printf '    IdentitiesOnly yes\n'
            printf '    StrictHostKeyChecking %s\n\n' "$shk"
        done
    } >"$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$dropin"
}

# Detect a pre-existing IdentityFile that would shadow the key `add` intends to
# install for <alias> (issue #1132 defect A). `ssh -G <alias>` prints every
# identity ssh would actually try; an explicit `Host` block suppresses the
# built-in defaults, so if our intended key ($2, tilde-expanded absolute) is
# NOT among them a hand-written block is winning. In that case echo the identity
# ssh WOULD use (its first `identityfile`, in the original ~-form) and return 0.
# Return 1 silently when there is no conflict, no output, or ssh is unavailable.
ssh_config_conflicting_identity() {
    _cci_al="$1"
    _cci_want="$2"
    _cci_ssh="${DEVX_SSH_BIN:-ssh}"
    command -v "$_cci_ssh" >/dev/null 2>&1 || return 1
    _cci_ids="$("$_cci_ssh" -G "$_cci_al" 2>/dev/null | awk 'tolower($1)=="identityfile"{print $2}')"
    [ -n "$_cci_ids" ] || return 1
    _cci_first=""
    for _cci_id in $_cci_ids; do
        [ -n "$_cci_first" ] || _cci_first="$_cci_id"
        # Our intended key is offered → ssh will try it → no shadowing.
        [ "$(ssh_config_expand_tilde "$_cci_id")" = "$_cci_want" ] && return 1
    done
    printf '%s\n' "$_cci_first"
    return 0
}

# Ensure ~/.ssh/config includes the drop-in exactly once.
ssh_config_ensure_include() {
    main="$(ssh_config_main_path)"
    dropin="$(ssh_config_dropin_path)"
    dir="$(dirname "$main")"
    [ -d "$dir" ] || mkdir -p "$dir"
    [ -f "$main" ] || {
        : >"$main"
        chmod 600 "$main"
    }
    if ! grep -qF "Include $dropin" "$main" 2>/dev/null; then
        # Prepend Include — Host blocks before it would otherwise shadow it.
        tmp="${main}.tmp.$$"
        {
            printf 'Include %s\n\n' "$dropin"
            cat "$main"
        } >"$tmp"
        chmod 600 "$tmp"
        mv "$tmp" "$main"
    fi
}
