#!/usr/bin/env bash
# PostgreSQL service bootstrap & helpers
# file: ~/dotfiles/bash/app/postgresql.bash

# -------------------------------------------------
# Strict mode
# -------------------------------------------------
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    set -euo pipefail
else
    set -o pipefail
fi

# -------------------------------------------------
# 0) Configuration & Data Persistence
# -------------------------------------------------
PG_SERVICES_FILE="$HOME/.config/pg_services.list"
PGSERVICE_CONF="$HOME/.pg_service.conf"

# Check if config file exists
if [[ ! -f "$PG_SERVICES_FILE" ]]; then
    # Fail silently or warn if running interactively
    if [[ "$-" == *i* ]]; then
        # Only warn if we are not just sourcing
        true
    fi
    # Empty array to prevent errors
    services=()
else
    # Load services from file (Skip comments and empty lines)
    mapfile -t services < <(grep -v '^[[:space:]]*#' "$PG_SERVICES_FILE" | grep -v '^[[:space:]]*$')
fi

DEFAULT_HOST="${DEFAULT_HOST:-localhost}"
DEFAULT_PORT="${DEFAULT_PORT:-5432}"

# -------------------------------
# 1) Admin Helper (Internal)
# -------------------------------
# Executes SQL as superuser (tries sudo postgres first, then local postgres)
_admin_sql() {
    local db="${1:-postgres}"
    local query="${2:-}"
    local cmd=("sudo" "-u" "postgres" "psql" "-v" "ON_ERROR_STOP=1" "-X" "-q" "-d" "$db" "-c" "$query")

    # Try sudo first
    if ! printf "\q\n" | "${cmd[@]:0:4}" >/dev/null 2>&1; then
        # Fallback to local network connect
        cmd=("psql" "-h" "$DEFAULT_HOST" "-p" "$DEFAULT_PORT" "-U" "postgres" "-v" "ON_ERROR_STOP=1" "-X" "-q" "-d" "$db" "-c" "$query")
        if ! printf "\q\n" | "${cmd[@]:0:7}" >/dev/null 2>&1; then
            echo " [Error] Cannot connect to PostgreSQL as superuser."
            echo "         Please ensure you have sudo access or 'postgres' user password."
            return 1
        fi
    fi
    "${cmd[@]}"
}

# -------------------------------
# 2) Service Loading & Alias Generation
# -------------------------------
_generate_pg_service_conf() {
    {
        echo "# Autogenerated by postgresql.bash — $(date)"
        echo "# Do not edit manually. Edit $PG_SERVICES_FILE instead."
        echo ""
    } >"$PGSERVICE_CONF"
    chmod 0600 "$PGSERVICE_CONF"

    for entry in "${services[@]}"; do
        read -r svc db user pass <<<"$entry"
        {
            echo "[$svc]"
            echo "host=$DEFAULT_HOST"
            echo "port=$DEFAULT_PORT"
            echo "dbname=$db"
            echo "user=$user"
            echo "password=$pass"
            echo ""
        } >>"$PGSERVICE_CONF"
    done
}

_register_aliases() {
    # Clean old aliases
    while IFS= read -r name; do
        unset -f "${name}" 2>/dev/null
    done < <(declare -F | awk '{print $3}' | grep '^psql_')

    # Define new aliases
    for entry in "${services[@]}"; do
        read -r svc _ _ _ <<<"$entry"
        local func_name="psql_${svc}"
        eval "function ${func_name} { PGSERVICE=\"${svc}\" psql \"\$@\"; }"
    done
}

# Initial Load
if [[ -f "$PG_SERVICES_FILE" ]]; then
    _generate_pg_service_conf
    _register_aliases
fi

# -------------------------------
# 3) Core Commands: Add / Del
# -------------------------------

# [Interactive] Add a new service
psql_add() {
    local svc_name db_name db_user db_pass

    if [[ ! -f "$PG_SERVICES_FILE" ]]; then
        echo "[Error] Config file not found: $PG_SERVICES_FILE"
        echo "Please run './install.sh' to set up the symbolic link."
        return 1
    fi

    echo "=== Add New PostgreSQL Service ==="
    echo "Config File: $PG_SERVICES_FILE"

    # 1. Get Inputs
    read -r -p "1. Service Name (Alias suffix, e.g. my_dev): " svc_name
    if [[ -z "$svc_name" ]]; then
        echo "Aborted."
        return 1
    fi
    if grep -q "^$svc_name " "$PG_SERVICES_FILE"; then
        echo "Error: Service '$svc_name' already exists."
        return 1
    fi

    read -r -p "2. Database Name [default: $svc_name]: " db_name
    db_name=${db_name:-$svc_name}

    read -r -p "3. User Name [default: ${USER}]: " db_user
    db_user=${db_user:-$USER}

    read -r -s -p "4. Password: " db_pass
    echo
    if [[ -z "$db_pass" ]]; then
        echo "Password cannot be empty."
        return 1
    fi

    # 2. Save to config (Appends to the physical file, following symlink)
    # Using printf to ensure formatting aligns with the header
    printf "%s  %s  %s  %s\n" "$svc_name" "$db_name" "$db_user" "$db_pass" >>"$PG_SERVICES_FILE"
    echo " [Info] Added to $PG_SERVICES_FILE"

    # 3. Reload
    mapfile -t services < <(grep -v '^[[:space:]]*#' "$PG_SERVICES_FILE" | grep -v '^[[:space:]]*$')
    _generate_pg_service_conf
    _register_aliases

    # 4. Offer to create actual DB
    echo
    read -r -p "Do you want to CREATE this Database & User in PostgreSQL now? (y/n): " confirm
    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
        _psql_create_logic "$db_name" "$db_user" "$db_pass"
    fi

    echo "Done. Use 'psql_$svc_name' to connect."
}

# [Interactive] Delete a service
psql_del() {
    local svc_name
    local selection

    if [[ ! -f "$PG_SERVICES_FILE" ]]; then
        echo "[Error] Config file not found: $PG_SERVICES_FILE"
        return 1
    fi

    echo "=== Delete PostgreSQL Service ==="
    if [[ ${#services[@]} -eq 0 ]]; then
        echo "No services configured."
        return 0
    fi

    # List services
    local i=0
    for entry in "${services[@]}"; do
        read -r svc db user _ <<<"$entry"
        echo " [$i] $svc (DB: $db, User: $user)"
        ((i++))
    done

    read -r -p "Select number to delete (or 'q' to quit): " selection
    if [[ "$selection" == "q" ]]; then return 0; fi
    if ! [[ "$selection" =~ ^[0-9]+$ ]] || [[ "$selection" -ge "${#services[@]}" ]]; then
        echo "Invalid selection."
        return 1
    fi

    # Get details
    read -r svc_name db_name db_user _ <<<"${services[$selection]}"

    echo
    echo "Selected: $svc_name"
    read -r -p "Also DROP DATABASE '$db_name' and USER '$db_user' from PostgreSQL? (y/n/only-config): " confirm

    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
        # Drop DB
        echo " -> Terminating connections..."
        _admin_sql "postgres" "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${db_name}' AND pid <> pg_backend_pid();"
        echo " -> Dropping Database '$db_name'..."
        _admin_sql "postgres" "DROP DATABASE IF EXISTS ${db_name};"

        # Drop User (Optional check)
        echo " -> Attempting to drop User '$db_user'..."
        if ! _admin_sql "postgres" "DROP ROLE ${db_user};" 2>/dev/null; then
            echo "    (User not deleted. Likely used by other DBs or dependent objects)"
        else
            echo "    User deleted."
        fi
    fi

    # Remove from file (using temp file for safety)
    # Use a temp file to filter out the deleted line
    grep -v "^$svc_name " "$PG_SERVICES_FILE" >"${PG_SERVICES_FILE}.tmp" && mv "${PG_SERVICES_FILE}.tmp" "$PG_SERVICES_FILE"

    # Reload
    mapfile -t services < <(grep -v '^[[:space:]]*#' "$PG_SERVICES_FILE" | grep -v '^[[:space:]]*$')
    _generate_pg_service_conf
    _register_aliases

    echo "Service '$svc_name' removed."
}

# Internal logic for DB creation (Separated for reuse)
_psql_create_logic() {
    local db_name=$1
    local db_user=$2
    local db_pass=$3

    echo "==> Configuring User '$db_user'..."
    # Check if role exists
    local exists
    exists=$(_admin_sql "postgres" "SELECT 1 FROM pg_roles WHERE rolname='$db_user'" -tA)
    if [[ "$exists" != "1" ]]; then
        _admin_sql "postgres" "CREATE ROLE $db_user LOGIN PASSWORD '$db_pass';"
    else
        _admin_sql "postgres" "ALTER ROLE $db_user WITH LOGIN PASSWORD '$db_pass';"
    fi

    echo "==> Creating Database '$db_name'..."
    exists=$(_admin_sql "postgres" "SELECT 1 FROM pg_database WHERE datname='$db_name'" -tA)
    if [[ "$exists" != "1" ]]; then
        _admin_sql "postgres" "CREATE DATABASE $db_name OWNER $db_user TEMPLATE template0 ENCODING 'UTF8';"
    else
        echo "    (Database already exists)"
    fi

    echo "==> Applying Privileges..."
    _admin_sql "$db_name" "REVOKE CONNECT ON DATABASE $db_name FROM PUBLIC;"
    _admin_sql "$db_name" "GRANT CONNECT ON DATABASE $db_name TO $db_user;"
    _admin_sql "$db_name" "GRANT ALL PRIVILEGES ON DATABASE $db_name TO $db_user;"
    _admin_sql "$db_name" "ALTER SCHEMA public OWNER TO $db_user;"
}

# -------------------------------
# 4) User Management Command
# -------------------------------
psql_user() {
    local action="${1:-list}"
    local arg1="$2"
    local arg2="$3"

    case "$action" in
    list)
        echo "=== PostgreSQL Users ==="
        _admin_sql "postgres" "\du"
        ;;
    create)
        if [[ -z "$arg1" ]]; then
            read -r -p "Enter new username: " arg1
        fi
        if [[ -z "$arg1" ]]; then
            echo "Cancelled."
            return 1
        fi

        read -r -s -p "Enter password for '$arg1': " arg2
        echo
        echo "Creating user '$arg1'..."
        _admin_sql "postgres" "CREATE USER $arg1 WITH PASSWORD '$arg2';" && echo "Success."
        ;;
    delete)
        if [[ -z "$arg1" ]]; then
            read -r -p "Enter username to DELETE: " arg1
        fi
        if [[ -z "$arg1" ]]; then
            echo "Cancelled."
            return 1
        fi

        read -r -p "Are you sure you want to delete user '$arg1'? (y/N): " confirm
        if [[ "$confirm" == "y" ]]; then
            _admin_sql "postgres" "DROP USER $arg1;" && echo "User '$arg1' deleted."
        fi
        ;;
    rename)
        if [[ -z "$arg1" || -z "$arg2" ]]; then
            echo "Usage: psql_user rename <old_name> <new_name>"
            return 1
        fi
        echo "Renaming '$arg1' to '$arg2'..."
        _admin_sql "postgres" "ALTER USER $arg1 RENAME TO $arg2;" && echo "Success."
        ;;
    passwd)
        if [[ -z "$arg1" ]]; then
            read -r -p "Enter username to change password: " arg1
        fi
        read -r -s -p "Enter NEW password for '$arg1': " arg2
        echo
        _admin_sql "postgres" "ALTER USER $arg1 WITH PASSWORD '$arg2';" && echo "Password updated."
        ;;
    attr)
        if [[ -z "$arg1" ]]; then
            read -r -p "Enter username to modify attributes: " arg1
        fi
        if [[ -z "$arg1" ]]; then
            echo "Cancelled."
            return 1
        fi

        echo "=== Modifying Attributes for '$arg1' ==="
        echo " (Press 'y' to grant, any other key to revoke/skip)"

        local ans
        # 1. Create DB
        read -r -p "1. Allow DB Creation (CREATEDB)? [y/N]: " ans
        if [[ "$ans" =~ ^[Yy]$ ]]; then
            _admin_sql "postgres" "ALTER ROLE $arg1 WITH CREATEDB;"
            echo "   -> CREATEDB Granted."
        else
            _admin_sql "postgres" "ALTER ROLE $arg1 WITH NOCREATEDB;"
            echo "   -> CREATEDB Revoked."
        fi

        # 2. Create Role
        read -r -p "2. Allow Creating Users (CREATEROLE)? [y/N]: " ans
        if [[ "$ans" =~ ^[Yy]$ ]]; then
            _admin_sql "postgres" "ALTER ROLE $arg1 WITH CREATEROLE;"
            echo "   -> CREATEROLE Granted."
        else
            _admin_sql "postgres" "ALTER ROLE $arg1 WITH NOCREATEROLE;"
            echo "   -> CREATEROLE Revoked."
        fi

        # 3. Superuser
        read -r -p "3. Make SUPERUSER (Dangerous)? [y/N]: " ans
        if [[ "$ans" =~ ^[Yy]$ ]]; then
            _admin_sql "postgres" "ALTER ROLE $arg1 WITH SUPERUSER;"
            echo "   -> SUPERUSER Granted."
        else
            _admin_sql "postgres" "ALTER ROLE $arg1 WITH NOSUPERUSER;"
            echo "   -> SUPERUSER Revoked."
        fi

        echo "Done."
        _admin_sql "postgres" "\\du $arg1"
        ;;
    *)
        echo "Usage: psql_user <command>"
        echo "Commands:"
        echo "  list            : List all users"
        echo "  create <name>   : Create a new user"
        echo "  attr <name>     : Modify user attributes (Wizard)"
        echo "  delete <name>   : Delete a user"
        echo "  rename <old> <new> : Rename a user"
        echo "  passwd <name>   : Change password"
        ;;
    esac
}

# -------------------------------
# 5) Help & Wrapper
# -------------------------------
psqlhelp() {
    local bold blue green yellow reset
    bold=$(tput bold 2>/dev/null || echo "")
    blue=$(tput setaf 4 2>/dev/null || echo "")
    green=$(tput setaf 2 2>/dev/null || echo "")
    yellow=$(tput setaf 3 2>/dev/null || echo "")
    reset=$(tput sgr0 2>/dev/null || echo "")
    if [[ $# -gt 0 ]]; then
        # Legacy/Direct mode support: psqlhelp <service> <cmd>
        local svc="$1"
        shift
        local sql_cmd="$*"
        PGSERVICE="$svc" psql -c "$sql_cmd"
        return
    fi

    cat <<EOF
${bold}${blue}[PostgreSQL Manager]${reset}

    ${bold}${green}Services & DBs${reset}
        ${yellow}psql_add${reset}      : Add a new Service (Wizard: DB/User creation included)
        ${yellow}psql_del${reset}      : Remove a Service (Wizard: Drop DB/User option included)
        ${yellow}psql_<name>${reset}  : Connect to DB (e.g., psql_dmc_dev)

    ${bold}${green}User Management${reset}
        ${yellow}psql_user list${reset}           : List all users
        ${yellow}psql_user create <name>${reset}  : Create a new user
        ${yellow}psql_user attr <name>${reset}    : Modify attributes (CreateDB, Superuser...)
        ${yellow}psql_user rename <o> <n>${reset} : Rename a user
        ${yellow}psql_user passwd <name>${reset}  : Change password
        ${yellow}psql_user delete <name>${reset}  : Delete a user

    ${bold}${green}Server Control${reset}    
        ${yellow}psql_server status${reset} : Check server status (start/stop/restart)

    ${bold}${green}Current Services${reset}
EOF

    if [[ ${#services[@]} -eq 0 ]]; then
        echo "  (No services found. Run 'psql_add' or check configuration)"
    else
        # Simple Table View
        printf "\t  %-20s %-25s %-15s\n" "ALIAS" "DATABASE" "USER"
        printf "\t  %-20s %-25s %-15s\n" "-----" "--------" "----"
        for entry in "${services[@]}"; do
            read -r svc db user _ <<<"$entry"
            printf "\t  %-20s %-25s %-15s\n" "psql_$svc" "$db" "$user"
        done
    fi
    echo
    echo "    ${bold}${green}Config File${reset}: $PG_SERVICES_FILE"
    echo
}

# Server control wrapper (Legacy support)
psql_server() {
    local action="${1:-status}"
    if command -v systemctl >/dev/null 2>&1; then
        sudo systemctl "$action" postgresql
    else
        sudo service postgresql "$action"
    fi
}
