#!/usr/bin/env bash
# PostgreSQL service bootstrap & helpers
# file: ~/dotfiles/bash/app/postgresql.bash

# -------------------------------------------------
# Strict mode: 실행(run)일 때만 -euo 적용, source일 땐 pipefail만
# -------------------------------------------------
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    set -euo pipefail
else
    set -o pipefail
fi

: <<'POSTGRES_DOC'
==========================================================
PostgreSQL Dotfiles Helper - Getting Started Guide
==========================================================

1) 설치 (Ubuntu / WSL)
------------------------
sudo apt update
sudo apt install -y postgresql postgresql-contrib

1-추가) PostgreSQL 16 설치 (공식 APT 저장소 사용)
------------------------------------------------
※ Ubuntu 기본 저장소에는 PostgreSQL 16이 없을 수 있습니다.  
  PostgreSQL 공식 APT 저장소를 추가한 뒤 설치하세요.

# 1. PostgreSQL 공식 저장소 추가
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

# 2. 최신 방식으로 GPG 키 추가
curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

# 3. 권한 설정
sudo chmod 644 /etc/apt/trusted.gpg.d/postgresql.gpg

# 4. 업데이트 (경고 없이 실행되어야 함)
sudo apt update

# 5. PostgreSQL 16 설치
sudo apt install postgresql-16

# 6. 설치 확인
pg_lsclusters

2) PostgreSQL 서비스 관리
------------------------
# 서비스 시작
sudo service postgresql start
# 서비스 상태 확인
sudo service postgresql status   # active (running) 확인

3) postgres 슈퍼유저로 DB/유저 생성
-----------------------------------
sudo -u postgres psql <<'SQL'
-- 앱 전용 유저/DB 생성 (개발 / 테스트)
CREATE ROLE slea_user WITH LOGIN PASSWORD 'change_me_dev_password';
CREATE DATABASE sleassem_dev OWNER slea_user;
sudo -u postgres psql -c "ALTER USER slea_user WITH PASSWORD 'change_me_dev_password';"

-- 권한 부여
GRANT ALL PRIVILEGES ON DATABASE sleassem_dev TO slea_user;
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE sleassem_dev TO slea_user;"
SQL

4) 접속 테스트
---------------
psql "host=localhost dbname=sleassem_dev user=slea_user password=change_me_dev_password" -c "\l"

5) Dotfiles PostgreSQL Helper Functions
----------------------------------------
# 서비스 기반 psql 접속
psql_<service>   # 예: sleassem_dev, psql_dmc_dev

# 등록된 서비스와 URI 확인
psql_list [true] 
#   true 옵션: 서비스 목록만 간결하게 출력
#   false/없음: full URI 정보와 alias 포함

# psql 명령어 직접 실행
psql_cmd <service> <command>
# 예: psql_cmd dmc_dev \du
#      psql_cmd dmc_test "\dt"

# PostgreSQL 서버 제어
psql_server <start|stop|restart|reload|status>
# 예: psql_server start
#      psql_server status

==========================================================
POSTGRES_DOC

DEFAULT_HOST="${DEFAULT_HOST:-localhost}"
DEFAULT_PORT="${DEFAULT_PORT:-5432}"

# -------------------------------
# 0) Locale 설정 (WSL/Ubuntu Perl warning 제거용)
# -------------------------------
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# -------------------------------
# 1) 서비스 정의: "서비스명 DB명 사용자 비밀번호"
# -------------------------------
services=(
    "dmc_dev  dmc_playground_dev  dmc_user  change_me_strong_pw"
    "dmc_test dmc_playground_test dmc_user  change_me_strong_pw"
    "dmc_prod dmc_playground_prod dmc_user  change_me_strong_pw"
    "sleassem_dev sleassem_dev slea_user change_me_dev_password"
    "sleassem_test sleassem_test slea_user change_me_test_password"
    "sleassem_prod sleassem_prod slea_user change_me_prod_password"
)

PGSERVICE_FILE="$HOME/.pg_service.conf"
# 매번 새로 생성(초기화)하여 중복 누적 방지
{
    echo "# Autogenerated by postgresql.bash — $(date)"
    echo "# Permissions must stay 0600"
    echo
} >"$PGSERVICE_FILE"
chmod 0600 "$PGSERVICE_FILE"

# -------------------------------
# 3) 기존 psql_* function 삭제
# -------------------------------
while IFS= read -r name; do
    if [[ -n "${name}" ]]; then
        unset -f "${name}" 2>/dev/null
    fi
done < <(declare -F | awk '{print $3}' | grep '^psql_')

# Helper function to create dynamic psql service functions
_create_psql_service_function() {
    local service_name="$1"
    local func_name="psql_${service_name}"
    # Define the function dynamically using 'function' keyword for better compatibility
    eval "function ${func_name} { PGSERVICE=\"${service_name}\" psql \"\$@\"; }"
}

# -------------------------------
# 4) 서비스 배열 기반 설정/alias 생성
# -------------------------------
for entry in "${services[@]}"; do
    # shellcheck disable=SC2086
    read -r service_name db_name db_user db_pass <<<"$entry"

    # ~/.pg_service.conf 에 서비스 섹션 작성
    {
        echo "[$service_name]"
        echo "host=$DEFAULT_HOST"
        echo "port=$DEFAULT_PORT"
        echo "dbname=$db_name"
        echo "user=$db_user"
        echo "password=$db_pass"
        echo
    } >>"$PGSERVICE_FILE"

    # Create function instead of alias
    _create_psql_service_function "$service_name"
done

# -------------------------------
# 5) PostgreSQL alias list
# -------------------------------
psql_list() {
    local service_only="${1:-false}"
    if [[ "$service_only" == "true" ]]; then
        for entry in "${services[@]}"; do
            read -r service_name _ <<<"$entry"
            echo "psql_${service_name}=PGSERVICE=${service_name} psql"
        done
    else
        echo "Registered PostgreSQL aliases (current shell):"
        for entry in "${services[@]}"; do
            read -r service_name db_name db_user db_pass <<<"$entry"
            echo "psql_${service_name}=PGSERVICE=${service_name} psql | URI: postgresql://${db_user}:${db_pass}@${DEFAULT_HOST}:${DEFAULT_PORT}/${db_name}"
        done
    fi
}

# -------------------------------
# 6) PostgreSQL command helper (Updated)
# -------------------------------
psqlhelp() {
    # ---------- 색/스타일 ----------
    local _nocolor=false
    if [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
        if [[ $(tput colors 2>/dev/null || echo 0) -ge 8 ]]; then
            BOLD=$(tput bold)
            DIM=$(tput dim)
            RESET=$(tput sgr0)
            FG_CYAN=$(tput setaf 6)
            FG_GREEN=$(tput setaf 2)
            FG_YELLOW=$(tput setaf 3)
            FG_BLUE=$(tput setaf 4)
            FG_MAGENTA=$(tput setaf 5)
            FG_RED=$(tput setaf 1)
        else _nocolor=true; fi
    else _nocolor=true; fi
    
    if $_nocolor; then
        BOLD="" DIM="" RESET=""
        FG_CYAN="" FG_GREEN="" FG_YELLOW="" FG_BLUE="" FG_MAGENTA="" FG_RED=""
    fi

    # ---------- 인자/축약어 사전 ----------
    local service="${1:-}"
    shift || true
    local cmd="${*:-}"

    declare -A cmd_map=(
        ["du"]="du" ["l"]="l" ["dt"]="dt" ["d"]="d" ["q"]="q" ["x"]="x"
    )
    declare -A cmd_desc=(
        ["du"]="list roles" ["l"]="list databases" ["dt"]="list tables"
        ["d"]="describe table" ["q"]="quit" ["x"]="toggle expanded output"
    )

    # ---------- 화면 출력 함수 ----------
    _print_header() {
        printf "%s%s%s\n" "$BOLD$FG_CYAN" "$1" "$RESET"
    }

    _print_usage() {
        _print_header "Usage"
        cat <<USAGE
  ${BOLD}psqlhelp${RESET} ${FG_YELLOW}<service>${RESET} ${FG_GREEN}<command>${RESET}

${BOLD}Management Commands${RESET}
  ${FG_YELLOW}psql_create${RESET} <db_name>   : Create DB & User (Auto-hardening)
  ${FG_YELLOW}psql_delete${RESET} <service>   : Delete DB & Attempt to drop User

${BOLD}Examples${RESET}
  psqlhelp dmc_dev ${FG_GREEN}\\l${RESET}
  psqlhelp sleassem_dev ${FG_GREEN}dt${RESET}

${BOLD}Workflows${RESET}
  Add: Edit bash file -> psql_create -> Check
  Del: psql_delete -> Edit bash file
USAGE
        echo
    }

    _print_shortcuts() {
        _print_header "Shortcuts"
        for k in du l dt d x q; do
            printf "  %-3s %s→%s \\%-2s %s\n" "$BOLD$k$RESET" "$DIM" "$RESET" "${cmd_map[$k]}" "${cmd_desc[$k]}"
        done
        echo
    }
    _print_services_table() {
        _print_header "Available services (current shell)"

        # 1. [Logic] DB 목록 조회 (빠른 조회)
        local ALL_DBS=""
        local chk_svc chk_db chk_user chk_pass
        for entry in "${services[@]}"; do
            read -r chk_svc chk_db chk_user chk_pass <<<"$entry"
            if ALL_DBS=$(PGPASSWORD="$chk_pass" PGCONNECT_TIMEOUT=1 psql -h "${DEFAULT_HOST:-localhost}" -p "${DEFAULT_PORT:-5432}" -U "$chk_user" -d "$chk_db" -w -tAc "SELECT datname FROM pg_database" 2>/dev/null); then
                break
            fi
        done

        # ---------------------------------------------------------
        # 2. [Design] 컬럼 너비 설정 (이 숫자만 바꾸면 표 전체가 자동 조절됨)
        # ---------------------------------------------------------
        local w_stat=4    # STAT (아이콘/텍스트 너비)
        local w_svc=20    # SERVICE
        local w_alias=25  # ALIAS (조금 줄임)
        local w_db=25     # DB
        local w_user=12   # USER

        # ---------------------------------------------------------
        # 3. [Helper] 가로선 자동 생성 함수 (완벽한 줄맞춤의 핵심)
        # ---------------------------------------------------------
        # 사용법: _rep "문자" 반복횟수
        _rep() { printf "%0.s$1" $(seq 1 "$2"); }

        local line_stat line_svc line_alias line_db line_user
        line_stat=$(_rep "─" $((w_stat + 2)))   # 좌우 공백 1칸씩 포함(+2)
        line_svc=$(_rep "─" $((w_svc + 2)))
        line_alias=$(_rep "─" $((w_alias + 2)))
        line_db=$(_rep "─" $((w_db + 2)))
        line_user=$(_rep "─" $((w_user + 2)))

        # ---------------------------------------------------------
        # 4. [Output] 테이블 그리기
        # ---------------------------------------------------------
        
        # [Top Border]
        printf "${DIM}┌%s┬%s┬%s┬%s┬%s┐${RESET}\n" \
            "$line_stat" "$line_svc" "$line_alias" "$line_db" "$line_user"
        
        # [Header]
        printf "│ %-${w_stat}s │ %-${w_svc}s │ %-${w_alias}s │ %-${w_db}s │ %-${w_user}s │\n" \
            "STAT" "SERVICE" "ALIAS" "DB" "USER"

        # [Middle Separator]
        printf "${DIM}├%s┼%s┼%s┼%s┼%s┤${RESET}\n" \
             "$line_stat" "$line_svc" "$line_alias" "$line_db" "$line_user"

        local entry svc db user alias_name status_icon db_display user_display
        local db_padded user_padded svc_padded alias_padded

        for entry in "${services[@]}"; do
            read -r svc db user _ <<<"$entry"
            alias_name="psql_${svc}"
            
            # (A) 내용물 Padding (색상 입히기 전 길이 고정)
            printf -v svc_padded   "%-${w_svc}s"   "${svc:0:$w_svc}"     # 넘치면 자름
            printf -v alias_padded "%-${w_alias}s" "${alias_name:0:$w_alias}"
            printf -v db_padded    "%-${w_db}s"    "${db:0:$w_db}"
            printf -v user_padded  "%-${w_user}s"  "${user:0:$w_user}"

            # (B) 상태 결정 및 색상 입히기
            #     주의: status_icon은 Padding을 수동으로 제어하여 시각적 정렬 맞춤
            if [[ -z "$ALL_DBS" ]]; then
                # "? " (우측 공백 2칸)
                status_icon=" ${FG_YELLOW}?${RESET}  " 
                db_display="$db_padded"
            elif echo "$ALL_DBS" | grep -qx "$db"; then
                # " OK " (좌우 공백 1칸)
                status_icon=" ${FG_GREEN}OK${RESET} "
                db_display="${BOLD}${db_padded}${RESET}"
            else
                # "MISS" (공백 없음)
                status_icon="${FG_RED}MISS${RESET}"
                db_display="${DIM}${FG_RED}${db_padded}${RESET}"
            fi

            # (C) 최종 출력
            #     status_icon은 이미 색상코드 포함 길이가 제각각이므로 %s로 그냥 출력
            #     나머지는 이미 Padding 되었으므로 %s로 출력
            printf "│ %s │ %s │ %s │ %s │ %s │\n" \
                "$status_icon" "$svc_padded" "$alias_padded" "$db_display" "$user_padded"
        done

        # [Bottom Border]
        printf "${DIM}└%s┴%s┴%s┴%s┴%s┘${RESET}\n" \
             "$line_stat" "$line_svc" "$line_alias" "$line_db" "$line_user"
        
        if [[ -z "$ALL_DBS" ]]; then
             echo " ${FG_YELLOW}(!) Could not verify database status.${RESET}"
        fi
        echo
        printf "Run with:  %spsql_${DIM}<service>%s%s\n" "$BOLD" "$RESET" "  or  psqlhelp <service> <command>"
        echo
    }

    # ---------- 실행 로직 ----------
    if [[ -z "$service" || -z "$cmd" ]]; then
        _print_usage
        _print_shortcuts
        _print_services_table
        return 0  # return 1에서 0으로 변경 (단순 조회는 성공으로 간주)
    fi

    if [[ -n "${cmd_map[$cmd]:-}" && "${cmd:0:1}" != "\\" ]]; then
        cmd="\\${cmd_map[$cmd]}"
    fi

    printf "%s→%s Using service %s%s%s, executing %s%s%s\n" \
        "$DIM" "$RESET" "$BOLD$FG_MAGENTA" "$service" "$RESET" "$BOLD$FG_GREEN" "$cmd" "$RESET"

    PGSERVICE="$service" psql <<EOF
$cmd
EOF
}

# -------------------------------
# 7) PostgreSQL server 관리 함수
# -------------------------------
psql_server() {
    declare -A cmd_list=(
        ["start"]="start the PostgreSQL service"
        ["stop"]="stop the PostgreSQL service"
        ["restart"]="restart the PostgreSQL service"
        ["status"]="show PostgreSQL service status"
        ["reload"]="reload PostgreSQL configuration"
    )

    local action="${1:-}"
    if [[ -z "$action" ]]; then
        echo "Usage: psql_server <${!cmd_list[*]}>"
        return 1
    fi

    if [[ -n "${cmd_list[$action]:-}" ]]; then
        if command -v systemctl >/dev/null 2>&1; then
            echo "[Info] sudo systemctl $action postgresql"
            sudo systemctl "$action" postgresql
        else
            echo "[Info] sudo service postgresql $action"
            sudo service postgresql "$action"
        fi
    else
        echo "[Error] Unknown action: $action"
        return 1
    fi
}

# -------------------------------
# 8) WSL2 안내
# -------------------------------
# if grep -qEi "(Microsoft|WSL)" /proc/version &>/dev/null; then
#     echo ""
#     echo " [Info] WSL detected. Use 'sudo service postgresql start' instead of systemctl if needed."
# fi

# -------------------------------
# 9) Create DB quickly from services[] (psql_create <DB_NAME>)
# Example)
# 9.1) dmc_playground_prod 생성/하드닝 (services에 이미 정의돼 있으므로 비번 프롬프트 없이 진행)
#   psql_create dmc_playground_prod
# 9.2) services에 없는 DB를 만들 때 (비번 입력 프롬프트가 뜸)
#   psql_create my_new_db
# -------------------------------
psql_create() {
    local DB_NAME="${1:-}"
    if [[ -z "$DB_NAME" ]]; then
        echo "Usage: psql_create <DB_NAME>"
        return 1
    fi

    # 9-1) services 배열에서 DB_NAME 매칭하여 app_user/app_pass 추출
    local APP_USER="" APP_PASS="" SERVICE_HIT=""
    for entry in "${services[@]}"; do
        # shellcheck disable=SC2086
        read -r svc db user pass <<<"$entry"
        if [[ "$db" == "$DB_NAME" ]]; then
            APP_USER="$user"
            APP_PASS="$pass"
            SERVICE_HIT="$svc"
            break
        fi
    done
    # 매칭 실패 시 기본값/프롬프트
    if [[ -z "$APP_USER" ]]; then
        APP_USER="dmc_user"
        read -r -s -p "Enter password for role '$APP_USER': " APP_PASS
        echo
    fi

    # 9-2) admin psql 커맨드 선택 (sudo 우선, 실패 시 로컬 postgres 계정)
    local ADMIN_PSQL=("sudo" "-u" "postgres" "psql" "-v" "ON_ERROR_STOP=1" "-X" "-q")
    if ! printf "\\q\\n" | "${ADMIN_PSQL[@]}" >/dev/null 2>&1; then
        ADMIN_PSQL=("psql" "-h" "${DEFAULT_HOST:-localhost}" "-p" "${DEFAULT_PORT:-5432}" "-U" "postgres" "-v" "ON_ERROR_STOP=1" "-X" "-q")
        if ! printf "\\q\\n" | "${ADMIN_PSQL[@]}" >/dev/null 2>&1; then
            echo "[Error] Can't connect as postgres (sudo or local). Set up access and retry."
            return 1
        fi
    fi

    # 9-3) 도우미: admin 쿼리 실행
    _admin_sql() { "${ADMIN_PSQL[@]}" -d "${2:-postgres}" -c "$1"; }

    # 9-4) 역할 생성/비번 설정 (존재하면 비번만 보정)
    local ROLE_EXISTS
    ROLE_EXISTS=$("${ADMIN_PSQL[@]}" -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='${APP_USER}'" || true)
    if [[ "$ROLE_EXISTS" != "1" ]]; then
        echo "==> Creating role '${APP_USER}'..."
        _admin_sql "CREATE ROLE ${APP_USER} LOGIN PASSWORD \$\$${APP_PASS}\$\$;"
    else
        echo "==> Role '${APP_USER}' exists. Ensuring password..."
        _admin_sql "ALTER ROLE ${APP_USER} WITH LOGIN PASSWORD \$\$${APP_PASS}\$\$;"
    fi

    # 9-5) DB 생성 (없으면)
    local DB_EXISTS
    DB_EXISTS=$("${ADMIN_PSQL[@]}" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" || true)
    if [[ "$DB_EXISTS" != "1" ]]; then
        echo "==> Creating database '${DB_NAME}' owned by '${APP_USER}'..."
        _admin_sql "CREATE DATABASE ${DB_NAME} OWNER ${APP_USER} TEMPLATE template0 ENCODING 'UTF8';"
    else
        echo "==> Database '${DB_NAME}' already exists. Skipping create."
    fi

    # 9-6) 최소 하드닝 & 권한
    echo "==> Hardening connect privileges..."
    _admin_sql "REVOKE CONNECT ON DATABASE ${DB_NAME} FROM PUBLIC;"
    _admin_sql "GRANT  CONNECT ON DATABASE ${DB_NAME} TO ${APP_USER};"

    echo "==> Schema ownership & privileges..."
    _admin_sql "ALTER SCHEMA public OWNER TO ${APP_USER};" "${DB_NAME}"
    _admin_sql "REVOKE CREATE ON SCHEMA public FROM PUBLIC;" "${DB_NAME}"
    _admin_sql "GRANT USAGE, CREATE ON SCHEMA public TO ${APP_USER};" "${DB_NAME}"

    # 9-7) 요약/연동 안내
    echo "==> Done. Created/validated '${DB_NAME}' for user '${APP_USER}'."
    if [[ -n "$SERVICE_HIT" ]]; then
        echo "    Tip: psqlhelp ${SERVICE_HIT} \\l"
        echo "         psql_${SERVICE_HIT} -c '\\dt'"
    else
        echo "    (No service matched this DB in services[]. Consider adding one for convenience.)"
    fi
}

# -------------------------------
# 10) Delete DB & User safely (psql_delete <SERVICE_NAME>)
# -------------------------------
psql_delete() {
    local SERVICE_NAME="${1:-}"
    if [[ -z "$SERVICE_NAME" ]]; then
        echo "Usage: psql_delete <SERVICE_NAME>"
        echo "Example: psql_delete sleassem_dev"
        return 1
    fi

    # 10-1) 서비스 정보 조회
    local DB_NAME="" APP_USER="" FOUND=false
    for entry in "${services[@]}"; do
        read -r svc db user pass <<<"$entry"
        if [[ "$svc" == "$SERVICE_NAME" ]]; then
            DB_NAME="$db"
            APP_USER="$user"
            FOUND=true
            break
        fi
    done

    if [[ "$FOUND" == "false" ]]; then
        echo "[Error] Service '$SERVICE_NAME' not found in services list."
        echo "        Please check 'psqlhelp' for available services."
        return 1
    fi

    # 10-2) 삭제 확인 (Safety Check)
    echo "========================================================"
    echo " [WARNING] You are about to DELETE a database service."
    echo " Service : $SERVICE_NAME"
    echo " Database: $DB_NAME"
    echo " User    : $APP_USER"
    echo "========================================================"
    read -r -p "Are you sure you want to DESTROY this database? (Type 'delete'): " CONFIRM
    if [[ "$CONFIRM" != "delete" ]]; then
        echo "Aborted."
        return 0
    fi

    # 10-3) Admin 연결 설정 (psql_create와 동일 로직)
    local ADMIN_PSQL=("sudo" "-u" "postgres" "psql" "-v" "ON_ERROR_STOP=1" "-X" "-q")
    if ! printf "\\q\\n" | "${ADMIN_PSQL[@]}" >/dev/null 2>&1; then
        ADMIN_PSQL=("psql" "-h" "${DEFAULT_HOST:-localhost}" "-p" "${DEFAULT_PORT:-5432}" "-U" "postgres" "-v" "ON_ERROR_STOP=1" "-X" "-q")
        if ! printf "\\q\\n" | "${ADMIN_PSQL[@]}" >/dev/null 2>&1; then
            echo "[Error] Can't connect as postgres superuser."
            return 1
        fi
    fi
    _admin_sql() { "${ADMIN_PSQL[@]}" -d "${2:-postgres}" -c "$1"; }

    # 10-4) 활성 세션 강제 종료 (DB 삭제를 위해 필수)
    echo "==> Terminating active connections to '$DB_NAME'..."
    _admin_sql "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${DB_NAME}' AND pid <> pg_backend_pid();"

    # 10-5) DB 삭제
    echo "==> Dropping database '$DB_NAME'..."
    if _admin_sql "DROP DATABASE IF EXISTS ${DB_NAME};"; then
        echo "    Database deleted."
    else
        echo "[Error] Failed to drop database."
        return 1
    fi

    # 10-6) 유저 삭제 시도 (다른 DB가 공유 중이면 실패함 - 정상)
    echo "==> Attempting to drop role '$APP_USER'..."
    # 2>&1로 에러 메시지를 캡처하여 사용자 친화적으로 보여줌
    local DROP_USER_MSG
    if DROP_USER_MSG=$("${ADMIN_PSQL[@]}" -d postgres -c "DROP ROLE ${APP_USER};" 2>&1); then
        echo "    Role '$APP_USER' deleted (No other dependencies)."
    else
        # 에러가 'dependent' 관련이면 경고만 하고 넘어감
        if [[ "$DROP_USER_MSG" == *"dependent"* ]]; then
             echo "    [Skip] Role '$APP_USER' was NOT deleted because other databases still use it."
        else
             echo "    [Info] $DROP_USER_MSG"
        fi
    fi

    # ---------------------------------------------------------
    # [NEW] 10-7) 현재 쉘 세션 메모리에서 서비스 제거 (UX 개선)
    # ---------------------------------------------------------
    local i
    for i in "${!services[@]}"; do
        # 해당 서비스 이름으로 시작하는 항목 찾기
        if [[ "${services[i]}" =~ ^${SERVICE_NAME}[[:space:]] ]]; then
            unset 'services[i]'
            break
        fi
    done
    # 배열 인덱스 재정렬 (구멍 메우기)
    services=("${services[@]}")

    # ---------------------------------------------------------
    # 10-8) 마무리 안내
    # ---------------------------------------------------------
    echo ""
    echo "Done."
    echo "IMPORTANT: The service is removed from current shell, but..."
    echo "           You MUST remove the line for '$SERVICE_NAME' in ~/dotfiles/bash/app/postgresql.bash manually"
    echo "           to prevent it from reappearing next time you open a terminal."
}