#!/bin/sh
# shell-common/functions/file_cleanup.sh
# Interactive cleanup for backup/original files in the current directory.
#
# NOTE: shebang is POSIX /bin/sh per the shell-common policy, but the body
# below uses bash/zsh array syntax (`find_args+=(...)`,
# `CLEANUP_DEFAULT_PATTERNS=(...)`). That's safe because shell-common files
# are sourced by bash/zsh — never executed under pure dash. The zsh-compat
# `emulate -L sh` hook inside `del_file` keeps the syntax legal when sourced
# from zsh.

case $- in *i*) ;; *) [ -n "${DOTFILES_FORCE_INIT-}" ] || return 0 ;; esac

_cleanup_set_default_patterns() {
    CLEANUP_DEFAULT_PATTERNS=(
        '.*backup*'
        '.*.bak*'
        '.*-original'
    )
}

# Home-directory whitelist (issue #806). Narrower than the generic defaults
# so `clean-home` only targets the known dotfiles backup-accumulation
# patterns plus the post-migration fixed-suffix files.
_cleanup_set_home_patterns() {
    CLEANUP_HOME_PATTERNS=(
        '.zshrc.original'
        '.zshrc-*-original'
        '.zshrc.backup'
        '.zshrc.backup.*'
        '.npmrc.backup'
        '.npmrc.backup.*'
        '.npmrc.bak.*'
        '*.backup'
        '*.backup.*'
        '*-original'
        '*.bak'
        '*.bak.*'
    )
}

# Cache-file whitelist (issue #1216). zsh completion cache (.zcompdump*) is
# regenerated by compinit, not a backup — kept separate from
# CLEANUP_HOME_PATTERNS so it's an opt-in cleanup, not bundled into
# clean-home's default sweep.
_cleanup_set_cache_patterns() {
    CLEANUP_CACHE_PATTERNS=(
        '.zcompdump'
        '.zcompdump-*'
    )
}

# In home mode, offer to remove the legacy ~/dotfiles-backup/ directory.
# Interactive (confirm); a decline or a missing directory is a no-op.
_cleanup_offer_dotfiles_backup_dir() {
    local home_dir="$1"
    local backup_dir="${home_dir}/dotfiles-backup"

    [ -d "$backup_dir" ] || return 0

    ux_section "dotfiles-backup/ Directory"
    ux_bullet "$backup_dir"
    if ux_confirm "Remove the entire ${backup_dir} directory?" "n"; then
        if rm -rf -- "$backup_dir"; then
            ux_success "Removed: $backup_dir"
        else
            ux_error "Failed to remove: $backup_dir"
        fi
    else
        ux_info "Skipped: $backup_dir"
    fi
}

# In cache mode, offer to remove stale .zcompdump-*.lock/ directories left
# behind by an interrupted compinit run. _cleanup_collect_matches only
# finds -type f, so these directories never show up in the file preview —
# they need their own confirm-and-remove step, same shape as the
# dotfiles-backup offer above but glob-driven since the host suffix varies.
_cleanup_offer_cache_lock_dirs() {
    local search_dir="$1"
    local lock_matches=""
    local lock_dir=""

    lock_matches="$(find "$search_dir" -maxdepth 1 -type d -name '.zcompdump-*.lock' -print 2>/dev/null | LC_ALL=C sort -u)"
    [ -n "$lock_matches" ] || return 0

    while IFS= read -r lock_dir; do
        [ -n "$lock_dir" ] || continue
        ux_section "Stale zcompdump Lock Directory"
        ux_bullet "$lock_dir"
        if ux_confirm "Remove ${lock_dir}?" "n"; then
            if rm -rf -- "$lock_dir"; then
                ux_success "Removed: $lock_dir"
            else
                ux_error "Failed to remove: $lock_dir"
            fi
        else
            ux_info "Skipped: $lock_dir"
        fi
    done <<EOF
$lock_matches
EOF
}

_cleanup_collect_matches() {
    local search_dir="$1"
    shift

    local find_args=("$search_dir" -maxdepth 1 -type f "(")
    local first_pattern=1
    local pattern=""

    for pattern in "$@"; do
        if [ "$first_pattern" -eq 0 ]; then
            find_args+=(-o)
        fi
        find_args+=(-name "$pattern")
        first_pattern=0
    done
    find_args+=(")")

    CLEANUP_MATCHES_OUTPUT="$(find "${find_args[@]}" -print 2>/dev/null | LC_ALL=C sort -u)"
}

_cleanup_file_size() {
    local file="$1"
    CLEANUP_FILE_SIZE="$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || printf '%s\n' '?')"
}

_cleanup_preview() {
    local search_dir="$1"
    shift

    local patterns=("$@")
    local files=()
    local matches=""
    local file=""

    _cleanup_collect_matches "$search_dir" "${patterns[@]}"
    matches="$CLEANUP_MATCHES_OUTPUT"
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        files+=("$file")
    done <<EOF
$matches
EOF

    ux_header "File Cleanup Preview"
    ux_section "Target Directory"
    ux_bullet "$search_dir"

    ux_section "Patterns"
    for file in "${patterns[@]}"; do
        ux_bullet "$file"
    done

    if [ "${#files[@]}" -eq 0 ]; then
        ux_warning "No matching files found"
        return 1
    fi

    ux_section "Matched Files (${#files[@]})"
    for file in "${files[@]}"; do
        local size=""
        _cleanup_file_size "$file"
        size="$CLEANUP_FILE_SIZE"
        ux_bullet "$(basename "$file") ($size bytes)"
    done

    DEL_FILE_MATCHED_FILES=("${files[@]}")
    return 0
}

_cleanup_delete_one() {
    local file="$1"
    if rm -f -- "$file" 2>/dev/null; then
        ux_success "Deleted: $file"
        return 0
    fi

    ux_error "Failed to delete: $file"
    return 1
}

_cleanup_delete_all() {
    local files=("$@")
    local file=""
    local success_count=0
    local error_count=0

    if ! ux_confirm "Delete all ${#files[@]} file(s)?" "n"; then
        ux_info "Operation cancelled"
        return 0
    fi

    ux_section "Deleting Files"
    for file in "${files[@]}"; do
        if _cleanup_delete_one "$file"; then
            success_count=$((success_count + 1))
        else
            error_count=$((error_count + 1))
        fi
    done

    ux_section "Summary"
    if [ "$error_count" -eq 0 ]; then
        ux_success "$success_count file(s) deleted successfully"
        return 0
    fi

    ux_warning "$success_count succeeded, $error_count failed"
    return 1
}

_cleanup_delete_individually() {
    local files=("$@")
    local file=""
    local success_count=0
    local skip_count=0
    local error_count=0

    ux_section "Review Each File"
    for file in "${files[@]}"; do
        if ux_confirm "Delete $(basename "$file")?" "n"; then
            if _cleanup_delete_one "$file"; then
                success_count=$((success_count + 1))
            else
                error_count=$((error_count + 1))
            fi
        else
            ux_info "Skipped: $file"
            skip_count=$((skip_count + 1))
        fi
    done

    ux_section "Summary"
    ux_success "$success_count file(s) deleted"
    ux_info "$skip_count file(s) skipped"
    if [ "$error_count" -gt 0 ]; then
        ux_warning "$error_count file(s) failed"
        return 1
    fi

    return 0
}

_cleanup_select_mode() {
    ux_section "Choose Deletion Mode"
    ux_bullet "1  Delete all matched files"
    ux_bullet "2  Review each matched file"
    ux_bullet "0  Cancel"

    while true; do
        printf "%s❯%s Select 0, 1, or 2: " "${UX_INFO}" "${UX_RESET}"
        read -r DEL_FILE_SELECTION
        case "$DEL_FILE_SELECTION" in
            0|1|2)
                return 0
                ;;
            *)
                ux_error "Invalid input. Enter 0, 1, or 2."
                ;;
        esac
    done
}

# Public help topic for my-help integration. Registered in
# shell-common/functions/my_help.sh (HELP_DESCRIPTIONS + HELP_CATEGORY_MEMBERS[cli]).
del_file_help() {
    ux_header "del-file"
    ux_usage "del-file" "[--home|--cache] [pattern...]" "Interactively delete backup/original/cache files"
    ux_section "Default patterns (current directory)"
    ux_bullet ".*backup*"
    ux_bullet ".*.bak*"
    ux_bullet ".*-original"
    ux_section "--home  (alias: clean-home)"
    ux_bullet "Targets \$HOME with a dotfiles backup whitelist (.backup / -original / .bak)"
    ux_bullet "Also offers to remove the legacy ~/dotfiles-backup/ directory"
    ux_section "--cache"
    ux_bullet "Targets \$HOME for zsh completion cache (.zcompdump*)"
    ux_bullet "Also offers to remove stale .zcompdump-*.lock/ directories"
    ux_section "Examples"
    ux_bullet "del-file                # current dir, use defaults"
    ux_bullet "del-file '*.tmp'        # extend with one extra pattern"
    ux_bullet "clean-home              # clean accumulated ~/ backups (issue #806)"
    ux_bullet "del-file --cache        # clean ~/.zcompdump* cache files (issue #1216)"
    ux_info "Next: del-file (interactive — preview, then choose 1/2/0)"
}

del_file() {
    [ -n "${ZSH_VERSION:-}" ] && emulate -L sh

    # Parse options in a loop so help works regardless of flag order
    # (e.g. `clean-home --help` == `del_file --home --help`), and unknown
    # flags are rejected instead of being treated as cleanup patterns.
    local home_mode=0
    local cache_mode=0
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help|help) del_file_help; return 0 ;;
            --home) home_mode=1; shift ;;
            --cache) cache_mode=1; shift ;;
            -*) ux_error "del-file: unknown option $1"; return 1 ;;
            *) break ;;
        esac
    done

    if [ "$home_mode" -eq 1 ] && [ "$cache_mode" -eq 1 ]; then
        ux_error "del-file: --home and --cache are mutually exclusive"
        return 1
    fi

    if [ ! -t 0 ] || [ ! -t 1 ]; then
        ux_error "del-file requires an interactive terminal"
        return 1
    fi

    local search_dir=""
    local patterns=()
    local extra_pattern=""
    local default_pattern=""
    local selection=""

    if [ "$home_mode" -eq 1 ]; then
        search_dir="${HOME}"
        _cleanup_set_home_patterns
        for default_pattern in "${CLEANUP_HOME_PATTERNS[@]}"; do
            [ -n "$default_pattern" ] || continue
            patterns+=("$default_pattern")
        done
    elif [ "$cache_mode" -eq 1 ]; then
        search_dir="${HOME}"
        _cleanup_set_cache_patterns
        for default_pattern in "${CLEANUP_CACHE_PATTERNS[@]}"; do
            [ -n "$default_pattern" ] || continue
            patterns+=("$default_pattern")
        done
    else
        search_dir="${PWD}"
        _cleanup_set_default_patterns
        for default_pattern in "${CLEANUP_DEFAULT_PATTERNS[@]}"; do
            [ -n "$default_pattern" ] || continue
            patterns+=("$default_pattern")
        done
    fi

    for extra_pattern in "$@"; do
        [ -n "$extra_pattern" ] || continue
        patterns+=("$extra_pattern")
    done

    # Home mode also cleans the legacy ~/dotfiles-backup/ directory.
    if [ "$home_mode" -eq 1 ]; then
        _cleanup_offer_dotfiles_backup_dir "$search_dir"
    fi

    # Cache mode also cleans stale .zcompdump-*.lock/ directories.
    if [ "$cache_mode" -eq 1 ]; then
        _cleanup_offer_cache_lock_dirs "$search_dir"
    fi

    if ! _cleanup_preview "$search_dir" "${patterns[@]}"; then
        # In home/cache mode the directory cleanup above may already have
        # done useful work, so a "no matching files" result is not an error.
        [ "$home_mode" -eq 1 ] && return 0
        [ "$cache_mode" -eq 1 ] && return 0
        return 1
    fi

    ux_section "Deletion Modes"
    ux_bullet "Delete all   Delete every matched file after one confirmation"
    ux_bullet "Review each  Ask once per file before deleting"
    ux_bullet "Cancel       Do nothing"

    _cleanup_select_mode || return 0
    selection="$DEL_FILE_SELECTION"

    case "$selection" in
        1)
            _cleanup_delete_all "${DEL_FILE_MATCHED_FILES[@]}"
            ;;
        2)
            _cleanup_delete_individually "${DEL_FILE_MATCHED_FILES[@]}"
            ;;
        *)
            ux_info "Operation cancelled"
            return 0
            ;;
    esac
}

alias del-file='del_file'
# Home-directory backup cleanup (issue #806).
alias clean-home='del_file --home'
